openapi: 3.0.1
info:
  title: API Multi-tenant de Usuarios, Productos y Compras
  description: Documentación Swagger para los microservicios del proyecto final.
  version: 1.0.0

servers:
  - url: https://5efu0bvbt2.execute-api.us-east-1.amazonaws.com/dev
    description: Entorno de desarrollo

components:
  schemas:
    Usuario:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    Producto:
      type: object
      properties:
        product_id:
          type: string
        name:
          type: string
        price:
          type: number
        description:
          type: string
        stock:
          type: integer
    Compra:
      type: object
      properties:
        compra_id:
          type: string
        user_id:
          type: string
        items:
          type: array
          items:
            type: object
            properties:
              product_id:
                type: string
              quantity:
                type: integer
              price:
                type: number


paths:

  /users/signup:
    post:
      tags: [Usuarios]
      summary: Registro de nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado
        '400':
          description: Error en los datos

  /users/login:
    post:
      tags: [Usuarios]
      summary: Login de usuario y retorno de token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '200':
          description: Token válido
        '401':
          description: Credenciales inválidas

  /products:
    get:
      tags: [Productos]
      summary: Listar productos
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
        - name: lastKey
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Lista de productos
    post:
      tags: [Productos]
      summary: Crear un nuevo producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '201':
          description: Producto creado

  /products/{product_id}:
    get:
      tags: [Productos]
      summary: Obtener producto por ID
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
    put:
      tags: [Productos]
      summary: Modificar producto existente
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Producto'
      responses:
        '200':
          description: Producto actualizado
    delete:
      tags: [Productos]
      summary: Eliminar producto
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Producto eliminado

  /purchases:
    post:
      tags: [Compras]
      summary: Registrar una compra
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Compra'
      responses:
        '201':
          description: Compra registrada

  /purchases/{user_id}:
    get:
      tags: [Compras]
      summary: Obtener compras por usuario
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de compras
