openapi: 3.0.1
info:
  title: API Multi‑tenant de Usuarios, Productos y Compras
  description: Documentación Swagger para los microservicios del proyecto final.
  version: 1.0.0

servers:
  - url: https://m34zhwbth7.execute-api.us-east-1.amazonaws.com/dev/
    description: Entorno de desarrollo AWS

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Usuario:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    Producto:
      type: object
      required:
        - product_id
        - name
        - price
        - stock
      properties:
        product_id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float
        description:
          type: string
        stock:
          type: integer
          minimum: 0

    ItemCompra:
      type: object
      required:
        - product_id
        - quantity
        - price
      properties:
        product_id:
          type: string
        quantity:
          type: integer
          minimum: 1
        price:
          type: number
          format: float

    Compra:
      type: object
      required:
        - compra_id
        - user_id
        - items
      properties:
        compra_id:
          type: string
        user_id:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemCompra'

security:
  - bearerAuth: []

paths:

  /users/register:
    post:
      tags:
        - Usuarios
      summary: Registro de nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuario creado
        '400':
          description: Error en los datos

  /users/login:
    post:
      tags:
        - Usuarios
      summary: Login de usuario y retorno de token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '200':
          description: Token válido
        '401':
          description: Credenciales inválidas

  /products/find:
    parameters:
      - name: tenant_id
        in: path
        required: true
        schema:
          type: string
        requestBody:
          required: true
          content:
            application/json:
            schema:
              $ref: '#/components/schemas/Producto'
    post:
      tags:
        - Productos
      summary: Obtener producto por ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Producto encontrado
        '404':
          description: No encontrado
    delete:
      tags:
        - Productos
      summary: Eliminar producto
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Producto eliminado
        '404':
          description: No encontrado