import type { Product, Order } from "@/types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Desodorante para hombre Body Spray en Aerosol para Hombre OLD SPICE Fresh pk x 2 fr x 150 ml",
    description: "Desodorante Old Spice Fresh en pack de 2 unidades",
    price: 23.9,
    originalPrice: 29.9,
    discount: 20,
    image: "/placeholder.png?height=300&width=300",
    category: "cuidado-personal",
    rating: 4.5,
    stock: 50,
    code: "OSP001",
  },
  {
    id: "2",
    name: "NIVEA Pack Bálsamo After shave Men Sensitive Protect fr x 100 ml + Gel de Afeitar fr x 200 ml + Desodorante Spray fr x 150 ml",
    description: "Pack completo de cuidado masculino Nivea",
    price: 59.9,
    originalPrice: 79.9,
    discount: 25,
    image: "/placeholder.png?height=300&width=300",
    category: "cuidado-personal",
    rating: 4.7,
    stock: 30,
    code: "NIV001",
  },
  {
    id: "3",
    name: "Smartphone Samsung Galaxy A54 5G 128GB",
    description: "Smartphone con pantalla de 6.4 pulgadas y cámara triple",
    price: 1299.0,
    originalPrice: 1499.0,
    discount: 13,
    image: "/placeholder.png?height=300&width=300",
    category: "electro",
    rating: 4.6,
    stock: 15,
    code: "SAM001",
  },
  {
    id: "4",
    name: "Televisor Smart TV LG 55 pulgadas 4K UHD",
    description: "Smart TV con tecnología 4K y sistema operativo webOS",
    price: 1899.0,
    image: "/placeholder.png?height=300&width=300",
    category: "electro",
    rating: 4.8,
    stock: 8,
    code: "LG001",
  },
  {
    id: "5",
    name: "Arroz Superior Costeño 5kg",
    description: "Arroz de grano largo, ideal para toda la familia",
    price: 18.5,
    image: "/placeholder.png?height=300&width=300",
    category: "supermercado",
    rating: 4.3,
    stock: 100,
    code: "ARR001",
  },
  {
    id: "6",
    name: "Aceite Vegetal Primor 1L",
    description: "Aceite vegetal 100% puro para cocinar",
    price: 12.9,
    image: "/placeholder.png?height=300&width=300",
    category: "supermercado",
    rating: 4.4,
    stock: 75,
    code: "ACE001",
  },
  {
    id: "7",
    name: "Laptop HP Pavilion 15.6 Intel Core i5",
    description: "Laptop con procesador Intel Core i5, 8GB RAM, 512GB SSD",
    price: 2299.0,
    originalPrice: 2599.0,
    discount: 12,
    image: "/placeholder.png?height=300&width=300",
    category: "electro",
    rating: 4.5,
    stock: 12,
    code: "HP001",
  },
  {
    id: "8",
    name: "Auriculares Bluetooth Sony WH-CH720N",
    description: "Auriculares inalámbricos con cancelación de ruido",
    price: 399.0,
    originalPrice: 499.0,
    discount: 20,
    image: "/placeholder.png?height=300&width=300",
    category: "electro",
    rating: 4.7,
    stock: 25,
    code: "SON001",
  },
]

export const mockOrders: Order[] = [
  {
    id: "ORD001",
    userId: "3",
    items: [
      {
        productId: "1",
        productName: "Desodorante Old Spice Fresh",
        quantity: 2,
        price: 23.9,
      },
      {
        productId: "5",
        productName: "Arroz Superior Costeño 5kg",
        quantity: 1,
        price: 18.5,
      },
    ],
    subtotal: 66.3,
    shipping: 15.0,
    total: 81.3,
    status: "delivered",
    createdAt: "2024-01-15T10:30:00Z",
  },
]
