name: CI/CD – Serverless

on:
  push:
    branches: [ dev, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api-compras, api-productos, api-usuarios ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Deploy ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: |
          npm ci
          npx serverless deploy --stage ${{ github.ref_name }}
