name: CI/CD – Serverless

on:
  push:
    branches: [ dev, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ api-usuarios ]
    
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js & Serverless
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g serverless serverless-python-requirements

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Deploy ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: sls deploy --stage ${{ github.ref_name }}
